## The makeCacheMatrix function takes a square matrix that is invertible
## and creates a special "matrix" object that can cache its inverse.
## cacheSolve takes the "matrix" object that makeCacheMatrix creates and 
## calculates the inverse.

## creates a special "matrix" object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y){
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinv <- function(inverse) i <<- inverse
  getinv <- function() i
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## Calculates the inverse of "matrix" object generated by makeCacheMAtrix

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  i <- x$getinv()
  if (!is.null(i)){
    message("getting cached data")
    return(i)
  }
  matrix_data <- x$get()
  i <- solve(matrix_data, ...)
  x$setinv(i)
  return(i)
}
